### ISSUE TITLE
In specific circumstances, the number of coarse channels cannot be determined

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/blimpy#156]
**Describe the bug**
If the telescope is GBT, number of coarse channels is always calculated.  Assume that the telescope is not GBT.  The number of coarse channels cannot be determined in 2 circumstances:
(1) The number of channels is > 2^20 (high resolution) and the number of fine channels is not evenly divisible by 2^20, 
(2) The number of channels is < 2^20 (low/medium resolution).

This needs a better diagnostic in class Reader, member function calc_n_coarse_chan().  The turbo_seti programmer or operator should be guided to explicitly specify the number of coarse channels in one of 2 ways:
(1) Source code: object = FindDoppler(datafile=..., ..., n_coarse_chan=N)
(2) Command line: turboSETI ... -n N ...

Note from @telegraphic:
"For Parkes GC data, the coarse channel is actually 128 MHz wide, but I'd suggest using -n 64 so you search 2 MHz at a time."

This issue was originally filed here: https://github.com/UCBerkeleySETI/turbo_seti/issues/118.

**To Reproduce**
1. Download this HDF5 file from the Parkes telescope: http://blpd7.ssl.berkeley.edu/PX600/blc00/guppi_58949_50426_6052121070_GC_A00_0001.0000.h5
2. Access file with FindDoppler(datafile=arg_file, max_drift=20, min_drift=0, out_dir=arg_dir).
   (from turbo_seti.find_doppler.find_doppler import FindDoppler)
3. See traceback.

**Expected behavior**
Give a more complete explanation accompanying ```raise``` execution.

**Setup**
 - Python version: 3.8
 - Blimpy version: current github
- Turbo SETI version: current github

**Additional context**
```
Traceback (most recent call last):

  File "/mnt/elkdata/linux-home-folder/seti_testing/turbo_seti_testing/do_basic.py", line 53, in <module>
    run_turbo_seti(1, H5PATH, OUT_DIR_BASE)

  File "/mnt/elkdata/linux-home-folder/seti_testing/turbo_seti_testing/do_basic.py", line 38, in run_turbo_seti
    fdop = FindDoppler(datafile=arg_file, max_drift=20, min_drift=0, out_dir=arg_dir)

  File "/usr/local/lib/python3.8/dist-packages/turbo_seti-1.3.2-py3.8-linux-x86_64.egg/turbo_seti/find_doppler/find_doppler.py", line 80, in __init__
    self.data_handle = DATAHandle(datafile, out_dir=out_dir, n_coarse_chan=n_coarse_chan, coarse_chans=coarse_chans)

  File "/usr/local/lib/python3.8/dist-packages/turbo_seti-1.3.2-py3.8-linux-x86_64.egg/turbo_seti/find_doppler/data_handler.py", line 70, in __init__
    self.data_list = self.__split_h5()

  File "/usr/local/lib/python3.8/dist-packages/turbo_seti-1.3.2-py3.8-linux-x86_64.egg/turbo_seti/find_doppler/data_handler.py", line 127, in __split_h5
    n_coarse_chan = int(fil_file.calc_n_coarse_chan())

  File "/home/elkins/.local/lib/python3.8/site-packages/blimpy/waterfall.py", line 273, in calc_n_coarse_chan
    n_coarse_chan = self.container.calc_n_coarse_chan(chan_bw)

  File "/home/elkins/.local/lib/python3.8/site-packages/blimpy/io/base_reader.py", line 260, in calc_n_coarse_chan
    raise ValueError(errmsg)

ValueError: blimpy:io:base_reader:calc_n_coarse_chan: nchans >= 2**20. Couldn't figure out n_coarse_chan
```

**Comment by texadactyl** [comment]
@telegraphic @luigifcruz

I found the issue in the "Blanking DC bin" code.
data_handler.py
load_data()
```
        #Blanking DC bin.
        if self.n_coarse_chan is not None:
            n_coarse_chan = self.n_coarse_chan
        else:
            n_coarse_chan = int(self.fil_file.calc_n_coarse_chan())
        if n_coarse_chan != self.fil_file.calc_n_coarse_chan():  ### <------------------------ HERE !
            logger.warning('The file/selection is not an integer number of coarse channels. This could have unexpected consequences. Let op!')
        self.fil_file.blank_dc(n_coarse_chan)
```
So, calc_n_coarse_chan() gets called in spite of override in FindDoppler() call or on turboSETI command line.
