### ISSUE TITLE
python setup.py install broken?

### ISSUE THREAD

**Issue by jeenriquez** [UCBerkeleySETI/blimpy#53]
It seems I can't do **python setup.py install**. 

```
$ python setup.py install
Download error on https://pypi.org/simple/pytest-runner/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661) -- Some packages may not be found!
Couldn't find index page for 'pytest-runner' (maybe misspelled?)
Download error on https://pypi.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661) -- Some packages may not be found!
No local packages or working download links found for pytest-runner
Traceback (most recent call last):
  File "setup.py", line 66, in <module>
    test_suite="tests",
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/__init__.py", line 130, in setup
    _install_setup_requires(attrs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/__init__.py", line 125, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/dist.py", line 514, in fetch_build_eggs
    replace_conflicting=True,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 773, in resolve
    replace_conflicting=replace_conflicting
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1056, in best_match
    return self.obtain(req, installer)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1068, in obtain
    return installer(requirement)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/dist.py", line 581, in fetch_build_egg
    return cmd.easy_install(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 670, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')
```

**Comment by telegraphic** [comment]
This looks like an issue with the host OS having an older version of SSL. Not sure what needs updating though, whether updating `pip` or another python package will do?

**Comment by jeenriquez** [comment]
thanks Danny, I'll check. By the was I only had this issue in my mac, and not at GBT

**Comment by jeenriquez** [comment]
```pip install pytest-runner ``` did the trick.  @gijzelaerr we need to add this to the dependencies for blimpy?

**Comment by jeenriquez** [comment]
I see this is already shown in setup.py:
```
      setup_requires=['pytest-runner'],
```

**Comment by jeenriquez** [comment]
@gijzelaerr any comments on this? I think we can close it.

**Comment by gijzelaerr** [comment]
hm, it is weird though, a python setup.py install should just work. Are you trying to do a clean `python setup.py install` in a new virtualenv?

**Comment by gijzelaerr** [comment]
@jeenriquez does a clean install solve the problem?

**Comment by jeenriquez** [comment]
I retried this after last update and it works now.
